development:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  username: israel.hill
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  username: israel.hill
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  host: ec2-23-21-193-140.compute-1.amazonaws.com
  port: 5432
  username: liwkgmfdfynwqn
  password: GeYwdQBJGsfsFzmJnNs7mtX0n2