development:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  username: israel.hill
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  username: israel.hill
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
  username: israel.hill
  host: localhost
  port: 5432